import translations from "./static.generated.json";
import type {Locale} from "./config";

type StaticLocale = Exclude<Locale, "en">;
type StaticCatalog = Record<StaticLocale, Record<string, string>>;

const catalog = translations as StaticCatalog;

/**
 * Localize interface copy that belongs to the codebase rather than Sanity.
 * English phrases are the stable keys, which keeps page templates readable
 * and lets the translation catalog be regenerated by the same DeepSeek
 * pipeline used for managed content.
 */
export function staticUi(locale: Locale, english: string): string {
  if (locale === "en") return english;
  return catalog[locale]?.[english] || english;
}

const countAndDurationWords: Record<
  Exclude<Locale, "en">,
  Record<string, string>
> = {
  es: {
    unit: "unidad",
    units: "unidades",
    week: "semana",
    weeks: "semanas",
    day: "día",
    days: "días",
    year: "año",
    years: "años",
  },
  fr: {
    unit: "unité",
    units: "unités",
    week: "semaine",
    weeks: "semaines",
    day: "jour",
    days: "jours",
    year: "an",
    years: "ans",
  },
  de: {
    unit: "Einheit",
    units: "Einheiten",
    week: "Woche",
    weeks: "Wochen",
    day: "Tag",
    days: "Tage",
    year: "Jahr",
    years: "Jahre",
  },
  it: {
    unit: "unità",
    units: "unità",
    week: "settimana",
    weeks: "settimane",
    day: "giorno",
    days: "giorni",
    year: "anno",
    years: "anni",
  },
};

export function localizeCountDuration(
  locale: Locale,
  value: string | null | undefined,
): string | null | undefined {
  if (locale === "en" || !value) return value;
  return value.replace(
    /\b(unit|units|week|weeks|day|days|year|years)\b/gi,
    (word) => countAndDurationWords[locale][word.toLowerCase()] || word,
  );
}
