import type {
  SolutionBySlugQueryResult,
  ProductBySlugQueryResult,
  ProductListQueryResult,
  TaxonomyQueryResult,
  SiteSettingsQueryResult,
  HomeQueryResult,
  HomeSeriesQueryResult,
  HomeSolutionsQueryResult,
  HomePostsQueryResult,
  PostListQueryResult,
  PostBySlugQueryResult,
} from './sanity.types'

/**
 * Front-end-facing types derived from the generated `solutionBySlugQuery`
 * result, so components consume the exact projected shape (content-model
 * principle 5 — types flow from the query, not hand-written interfaces).
 *
 * `sanity.types.ts` is generated by `npm run typegen`; do not edit it.
 */
export type SolutionData = NonNullable<SolutionBySlugQueryResult>
export type SolutionBlock = NonNullable<SolutionData['pageBuilder']>[number]
export type HeroBlockData = Extract<SolutionBlock, { _type: 'heroBlock' }>
export type CtaBlockData = Extract<SolutionBlock, { _type: 'ctaBlock' }>
export type TextBlockData = Extract<SolutionBlock, { _type: 'textBlock' }>
export type FaqsBlockData = Extract<SolutionBlock, { _type: 'faqsBlock' }>
export type SolutionProduct = NonNullable<SolutionData['products']>[number]
export type SolutionPackage = NonNullable<SolutionData['packages']>[number]
export type RichText = NonNullable<TextBlockData['body']>

// ── Product (PDP) ─────────────────────────────────────────────────────────
export type ProductData = NonNullable<ProductBySlugQueryResult>
export type ProductVariant = NonNullable<ProductData['variants']>[number]
export type ProductKeySpec = NonNullable<ProductData['keySpecs']>[number]
export type ProductSpecRow = NonNullable<ProductData['specDimensions']>[number]
export type ProductOemTerm = NonNullable<ProductData['oemTerms']>[number]
export type ProductSolutionPlacement = NonNullable<ProductData['solutionPlacements']>[number]
export type RelatedProduct = NonNullable<ProductData['related']>[number]
export type SiteSettingsData = NonNullable<SiteSettingsQueryResult>

// ── Catalog ───────────────────────────────────────────────────────────────
export type ProductCardData = ProductListQueryResult[number]
export type TaxonomyData = TaxonomyQueryResult
export type TaxonomyItem = TaxonomyData['series'][number]

// ── Home ──────────────────────────────────────────────────────────────────
export type HomeData = NonNullable<HomeQueryResult>
export type HomeSeries = HomeSeriesQueryResult[number]
export type HomeSolution = HomeSolutionsQueryResult[number]
export type HomePost = HomePostsQueryResult[number]

// ── Resources / blog ──────────────────────────────────────────────────────
export type PostListItem = PostListQueryResult[number]
export type PostData = NonNullable<PostBySlugQueryResult>
export type PostSolutionLink = NonNullable<PostData['solutions']>[number]
