/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type FaqsBlock = {
  _type: "faqsBlock";
  heading?: string;
  items?: Array<{
    question?: string;
    answer?: string;
    _type: "faqItem";
    _key: string;
  }>;
};

export type TextBlock = {
  _type: "textBlock";
  heading?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  audience?: Array<string>;
};

export type CtaBlock = {
  _type: "ctaBlock";
  heading?: string;
  body?: string;
  cta?: CtaLink;
  audience?: Array<string>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type HeroBlock = {
  _type: "heroBlock";
  eyebrow?: string;
  heading?: string;
  subheading?: string;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  cta?: CtaLink;
  audience?: Array<string>;
};

export type SolutionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "solution";
};

export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type OemReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "oem";
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type CtaLink = {
  _type: "ctaLink";
  label?: string;
  internal?:
    | SolutionReference
    | ProductReference
    | OemReference
    | PostReference;
  external?: string;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  salesEmail?: string;
  phone?: string;
  whatsapp?: string;
  responseTime?: string;
  showPrices?: boolean;
  companyAddress?: string;
  catalogPdf?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  frameFinishes?: Array<{
    name?: string;
    hex?: string;
    _type: "finish";
    _key: string;
  }>;
  upholsteryColors?: Array<{
    name?: string;
    hex?: string;
    _type: "upholsteryColor";
    _key: string;
  }>;
  solutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    eyebrow?: string;
    heading?: string;
    subheading?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    ctaPrimary?: CtaLink;
    ctaSecondary?: CtaLink;
    stats?: Array<{
      value?: string;
      label?: string;
      _type: "heroStat";
      _key: string;
    }>;
  };
  howWeWork?: {
    heading?: string;
    intro?: string;
    cards?: Array<{
      eyebrow?: string;
      title?: string;
      image?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      };
      body?: string;
      terms?: Array<{
        label?: string;
        value?: string;
        _type: "workTerm";
        _key: string;
      }>;
      cta?: CtaLink;
      _type: "workCard";
      _key: string;
    }>;
  };
  catalog?: {
    eyebrow?: string;
    heading?: string;
    intro?: string;
  };
  useCases?: {
    eyebrow?: string;
    heading?: string;
  };
  oemBanner?: {
    heading?: string;
    body?: string;
    cta?: CtaLink;
  };
  factory?: {
    eyebrow?: string;
    heading?: string;
    body?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    steps?: Array<{
      label?: string;
      _type: "factoryStep";
      _key: string;
    }>;
    cta?: CtaLink;
  };
  ipProtection?: {
    eyebrow?: string;
    heading?: string;
    intro?: string;
    items?: Array<{
      title?: string;
      lead?: string;
      body?: string;
      featured?: boolean;
      _type: "ipPoint";
      _key: string;
    }>;
    cta?: CtaLink;
  };
  insights?: {
    eyebrow?: string;
    heading?: string;
  };
  finalCta?: {
    heading?: string;
    body?: string;
    cta?: CtaLink;
  };
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  excerpt?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
  audience?: Array<string>;
  solutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Oem = {
  _id: string;
  _type: "oem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  pageBuilder?: Array<
    | ({
        _key: string;
      } & HeroBlock)
    | ({
        _key: string;
      } & CtaBlock)
    | ({
        _key: string;
      } & TextBlock)
    | ({
        _key: string;
      } & FaqsBlock)
  >;
  seo?: Seo;
};

export type Solution = {
  _id: string;
  _type: "solution";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  audience?: Array<string>;
  summary?: string;
  pageBuilder?: Array<
    | ({
        _key: string;
      } & HeroBlock)
    | ({
        _key: string;
      } & CtaBlock)
    | ({
        _key: string;
      } & TextBlock)
    | ({
        _key: string;
      } & FaqsBlock)
  >;
  products?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  seo?: Seo;
};

export type SeriesReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "series";
};

export type EquipmentReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "equipment";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  sku?: string;
  status?: "published" | "draft" | "archived";
  series?: SeriesReference;
  equipment?: EquipmentReference;
  equipmentTypes?: Array<
    {
      _key: string;
    } & EquipmentReference
  >;
  productionStatus?: "in_production" | "made_to_order" | "discontinued";
  shipsIn?: string;
  certifications?: Array<string>;
  priceDisplay?: "show" | "quote";
  price?: number;
  currency?: "USD" | "EUR" | "GBP" | "CNY";
  priceUnit?: string;
  priceNote?: string;
  pricing?: Array<{
    currency?: "USD" | "EUR" | "GBP" | "CNY";
    amount?: number;
    validUntil?: string;
    _type: "priceEntry";
    _key: string;
  }>;
  moq?: string;
  leadTime?: string;
  warranty?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  mainImageDimensionNote?: string;
  gallery?: Array<{
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    alt?: string;
    label?: string;
    _type: "galleryImage";
    _key: string;
  }>;
  keySpecs?: Array<{
    value?: string;
    unit?: string;
    label?: string;
    note?: string;
    _type: "keySpec";
    _key: string;
  }>;
  variants?: Array<{
    name?: string;
    skuSuffix?: string;
    isDefault?: boolean;
    description?: string;
    janka?: string;
    finish?: string;
    swatchColor?: string;
    _type: "variant";
    _key: string;
  }>;
  specDimensions?: Array<{
    label?: string;
    value?: string;
    _type: "specDimensionsRow";
    _key: string;
  }>;
  specWeight?: Array<{
    label?: string;
    value?: string;
    _type: "specWeightRow";
    _key: string;
  }>;
  specMechanism?: Array<{
    label?: string;
    value?: string;
    _type: "specMechanismRow";
    _key: string;
  }>;
  specMaterials?: Array<{
    label?: string;
    value?: string;
    _type: "specMaterialsRow";
    _key: string;
  }>;
  specPdf?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  specRevision?: string;
  oemTerms?: Array<{
    label?: string;
    value?: string;
    note?: string;
    _type: "oemTerm";
    _key: string;
  }>;
  relatedProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  brand?: string;
  mpn?: string;
  gtin13?: string;
  material?: string;
  dimensions?: string;
  weight?: string;
  warrantyUrl?: string;
  certs?: Array<{
    label?: string;
    url?: string;
    _type: "certLink";
    _key: string;
  }>;
  summary?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  order?: number;
};

export type Equipment = {
  _id: string;
  _type: "equipment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  order?: number;
};

export type Series = {
  _id: string;
  _type: "series";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  order?: number;
  skuLabel?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | FaqsBlock
  | TextBlock
  | CtaBlock
  | SanityImageAssetReference
  | HeroBlock
  | SolutionReference
  | ProductReference
  | OemReference
  | PostReference
  | CtaLink
  | Seo
  | SanityFileAssetReference
  | SiteSettings
  | Home
  | SanityImageCrop
  | SanityImageHotspot
  | Post
  | Slug
  | Oem
  | Solution
  | SeriesReference
  | EquipmentReference
  | Product
  | Equipment
  | Series
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
